# Generated by Django 5.2 on 2025-11-08 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Productora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Productora',
                'verbose_name_plural': 'Productoras',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('sinopsis', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('anio', models.PositiveSmallIntegerField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/peliculas/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('generos', models.ManyToManyField(blank=True, related_name='peliculas', to='catalogo.genero')),
                ('productora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peliculas', to='catalogo.productora')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('sinopsis', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('anio', models.PositiveSmallIntegerField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/series/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('generos', models.ManyToManyField(blank=True, related_name='series', to='catalogo.genero')),
                ('productora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='catalogo.productora')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('numero', models.PositiveIntegerField()),
                ('temporada', models.PositiveIntegerField(default=1)),
                ('duracion_min', models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='catalogo.serie')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['serie', 'temporada', 'numero'],
                'unique_together': {('serie', 'temporada', 'numero')},
            },
        ),
    ]
