# Generated by Django 5.2 on 2025-11-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='cantidad_capitulos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Capitulo',
        ),
    ]
